// Code generated by proto-gen-validator. DO NOT EDIT.
// source: github.com/vine-io/apimachinery/apis/meta/v1/meta.proto

package metav1

import (
	is "github.com/vine-io/vine/util/is"
)

func (m *TypeMeta) Validate() error {
	return m.ValidateE("")
}

func (m *TypeMeta) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}

func (m *ObjectMeta) Validate() error {
	return m.ValidateE("")
}

func (m *ObjectMeta) ValidateE(prefix string) error {
	errs := make([]error, 0)
	if len(m.Uuid) != 0 {
	}
	return is.MargeErr(errs...)
}

func (m *OwnerReference) Validate() error {
	return m.ValidateE("")
}

func (m *OwnerReference) ValidateE(prefix string) error {
	errs := make([]error, 0)
	return is.MargeErr(errs...)
}
